---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  tasks:

    - name: install apache2 and php packages and update the repository.
      package:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes


      #- name: Install apache2 for centos systems
      #yum:
              #name: httpd
        #state: latest
        #update_cache: yes
       #cache_valid_time: 3600
       #when:
           #- ansible_os_family == "RedHat"
          #- ansible_distribution == "CentOS"
