---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  tasks:
    - name: update repository index
      apt: 
        update_cache: yes

    - name: install apache2 package
      apt:
        name: apache2
        state: latest

    - name: add php support for package
      apt:
        name: libapache2-mod-php
        state: latest

